---
knit: bookdown::preview_chapter
---

## Identifying confounding factors (Reads)

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(scater, quietly = TRUE)
library(knitr)
options(stringsAsFactors = FALSE)
opts_chunk$set(out.width='90%', fig.align = 'center', echo=FALSE)
reads <- readRDS("data/tung/reads.rds")
reads.qc <- reads[rowData(reads)$use, colData(reads)$use]
endog_genes <- !rowData(reads.qc)$is_feature_control
```

```{r confound-pca-reads, fig.cap = "PCA plot of the tung data"}
tmp <- runPCA(
  reads.qc[endog_genes, ],
  exprs_values = "logcounts_raw"
)
plotPCA(
    tmp,
    colour_by = "batch",
    size_by = "total_features_by_counts"
)
```

```{r confound-find-pcs-total-features-reads, fig.cap = "PC correlation with the number of detected genes", fig.asp=1}
logcounts(reads.qc) <- assay(reads.qc, "logcounts_raw")
plotExplanatoryPCs(
  reads.qc[endog_genes, ],
  variables = "total_features_by_counts"
)
logcounts(reads.qc) <- NULL
```

```{r confound-find-expl-vars-reads, fig.cap = "Explanatory variables"}
plotExplanatoryVariables(
    reads.qc[endog_genes, ],
    exprs_values = "logcounts_raw",
    variables = c(
        "total_features_by_counts",
        "total_counts",
        "batch",
        "individual",
        "pct_counts_ERCC",
        "pct_counts_MT"
    )
)
```

```{r}
sessionInfo()
```
